name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PACKAGE_NAME: my-package-name
  PACKAGE_VERSION: ${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $PACKAGE_NAME:$PACKAGE_VERSION

    - name: Log in to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_UNLP }}

    - name: Tag and push Docker image
      run: |
        docker tag $PACKAGE_NAME:$PACKAGE_VERSION docker.pkg.github.com/${{ github.repository }}/$PACKAGE_NAME:$PACKAGE_VERSION
        docker push docker.pkg.github.com/${{ github.repository }}/$PACKAGE_NAME:$PACKAGE_VERSION

    - name: Create GitHub release
      uses: actions/create-release@v1
      with:
        tag_name: $PACKAGE_VERSION
        release_name: Release $PACKAGE_VERSION
        draft: false
        prerelease: false

    - name: Upload package to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: docker.pkg.github.com/${{ github.repository }}/$PACKAGE_NAME:$PACKAGE_VERSION
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_UNLP }}
